name: Plan

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ vars.PROD_SUBSCRIPTION_ID }}
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Initialize Terraform
      run: |
        cd $GITHUB_WORKSPACE/provision
        terraform init -backend-config="access_key=${{ secrets.STATE_ACCESS_KEY }}"
    - name: Run terraform apply
      run: |
        cd $GITHUB_WORKSPACE/provision
        terraform plan -var-file="prod.tfvars"
  